const ADD_NEW_STUDENT = "ADD_NEW_STUDENT";
const REMOVE = "REMOVE";
const EDIT = "EDIT";
const FETCH_LIST = 'FETCH_LIST';
const SORT_NAME = 'SORT_NAME';
const SORT_EMAIL = 'SORT_EMAIL';
const SHOW_ERROR = 'SHOW_ERROR';
const SHOW_LOADER = 'SHOW_LOADER';
const HIDE_LOADER = 'HIDE_LOADER';

export { ADD_NEW_STUDENT, REMOVE, EDIT, FETCH_LIST, SORT_NAME, SORT_EMAIL, SHOW_ERROR, SHOW_LOADER, HIDE_LOADER };
